apiVersion: vl
kind: Pod
metadata :
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers :
  - name: nginx-container
    image: nginx
    ports :
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: DBCON
      value: connectionstring
    command : ["/bin/sh","-c"]
    args: echo ${DBCON}"]




